[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PORT,NODE_ENV,SMTP_HOST,SMTP_PORT"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
